language: c

compiler:
  - clang
  - gcc

os:
  - linux
#  - osx

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libcunit1 libcunit1-doc libcunit1-dev
 
script: make && make test