language: c

compiler:
  - clang
  - gcc

os:
  - linux
#  - osx

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libcunit1 libcunit1-doc libcunit1-dev
 - sudo apt-get install -qq python-pip
 - sudo pip install cpp-coveralls PyYAML

env:
  matrix:
  - CONFIG=Cov
  - CONFIG=Release


script: make CONF=$CONFIG && make CONF=$CONFIG test

after_success:
  - if [ "$CONFIG" = "Cov" ] ; then coveralls --gcov-options '\-lp' ; fi

notifications:
  email: false
  webhooks:
    - https://coveralls.io/webhook?repo_token=I1YLdEIAI4Xz0lm7jRauwLwPzHOxD7O2p